######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 19 23:49:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT          += sql network xml

# Input
HEADERS += gmail.h
SOURCES += gmail.cpp main.cpp
